version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: hashicorp/terraform:0.12.13
  environment:
    TF_IN_AUTOMATION: true

jobs:
  init:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: aws auth
          command: mkdir ~/.aws; echo -e "[default]\naws_access_key_id=$AWS_KEY\naws_secret_access_key=$AWS_SECRET\n" > ~/.aws/credentials
      - run:
          name: init
          command: terraform init -input=false
      - persist_to_workspace:
          root: ~/repo
          paths: .
      - persist_to_workspace:
          root: ~/.aws
          paths: .
  plan:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - attach_workspace:
          at: ~/.aws
      - run:
          name: select workspace
          command: terraform workspace select dev
      - run:
          name: plan
          command: terraform plan -no-color -out=tfplan -input=false
      - store_artifacts:
          path: ~/repo/tfplan
          destination: tfplan
      - persist_to_workspace:
          root: ~/repo
          paths: .
      - persist_to_workspace:
          root: ~/.aws
          paths: .
  apply:
    requires:
      - hold
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - attach_workspace:
          at: ~/.aws
      - run:
          name: select workspace
          command: terraform workspace select dev
      - run:
          name: apply
          command: terraform apply -input=false -auto-approve tfplan
      - run:
          name: show
          command: terraform show -no-color > tfresult
      - store_artifacts:
          path: ~/repo/tfresult
          destination: tfresult
      - persist_to_workspace:
          root: ~/.aws
          paths: .

workflows:
  version: 2
  build_deploy:
    jobs:
      - init
      - plan:
          requires:
            - init
      - apply:
          requires:
            - plan
          filters:
            branches:
              only: 
                - master
